//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Companies = new HashSet<Company>();
            this.FilterCriterias = new HashSet<FilterCriteria>();
        }
    
        public int CategoryId { get; set; }
        public string Category1 { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<FilterCriteria> FilterCriterias { get; set; }
    }
}
