//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterCriteria
    {
        public FilterCriteria()
        {
            this.CompanyMetas = new HashSet<CompanyMeta>();
        }
    
        public int FilterCriteriaId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CriteriaText { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<CompanyMeta> CompanyMetas { get; set; }
    }
}
